"""生成更多金融知识文件 — 将金融知识扩展到1000+条

用法: python3 gen_finance_knowledge_more.py
"""

import os, json

KNOWLEDGE_DIR = "/mnt/d/neuroflow-model/knowledge_base"
os.makedirs(KNOWLEDGE_DIR, exist_ok=True)

# ════════════════════════════════════════════
# 金融知识扩展（1000+ 条）
# ════════════════════════════════════════════

KNOWLEDGE = [
    # ── 基础金融概念 ──
    "Finance is the study of money management and the process of acquiring needed funds",
    "Financial system comprises institutions markets and instruments facilitating capital flow",
    "Capital markets facilitate buying and selling of long term debt and equity securities",
    "Money markets handle short term debt instruments with maturities under one year",
    "Primary market is where new securities are issued and sold to initial investors",
    "Secondary market is where existing securities are traded among investors after initial issuance",
    "Liquidity measures how quickly an asset can be converted to cash without significant price impact",
    "Leverage uses borrowed capital to increase potential return on investment",
    "Arbitrage exploits price differences of same asset in different markets for risk free profit",
    
    # ── 股票市场深入 ──
    "Order book lists buy and sell orders for a security organized by price level",
    "Market order executes immediately at current market prices guaranteeing execution not price",
    "Limit order specifies maximum buy or minimum sell price guaranteeing price not execution",
    "Stop loss order triggers market sell when price falls below specified level to limit losses",
    "Bid ask spread is difference between highest buyer bid and lowest seller ask price",
    "Short selling involves borrowing shares you do not own and selling them hoping price falls",
    "Margin trading allows investors to borrow money from broker to purchase additional securities",
    "Day trading involves buying and selling securities within same trading day",
    "Swing trading holds positions for several days to capture short to medium term gains",
    "Position trading holds positions for weeks to months based on long term trends",
    "Scalping makes dozens or hundreds of trades daily capturing small price movements",
    "Dark pools are private exchanges where institutional investors trade large blocks anonymously",
    "Market maker provides liquidity by continuously quoting bid and ask prices for securities",
    "Circuit breaker halts trading when market drops by predetermined percentage to prevent panic selling",
    "IPO initial public offering is first sale of stock by a private company to public investors",
    "Secondary offering is sale of new or existing shares after company has gone public",
    "Stock split increases number of shares while reducing price per share keeping market cap same",
    "Reverse stock split reduces number of shares and increases price per share proportionally",
    "Stock buyback occurs when company purchases its own shares from the marketplace",
    "Dividend reinvestment plan DRIP automatically uses dividends to buy more company shares",
    "Rights offering gives existing shareholders opportunity to buy additional shares at discount",
    
    # ── 投资策略深入 ──
    "Core satellite strategy combines core index holdings with actively managed satellite positions",
    "Tactical asset allocation temporarily deviates from strategic targets to exploit market opportunities",
    "Constant proportion portfolio insurance CPPI guarantees minimum portfolio value through dynamic allocation",
    "Pairs trading identifies two historically correlated stocks and trades their temporary divergence",
    "Statistical arbitrage uses mathematical models to identify and exploit pricing inefficiencies",
    "Event driven strategy capitalizes on price movements caused by corporate events like mergers",
    "Global macro strategy makes investment decisions based on macroeconomic and political analysis",
    "Long short equity strategy buys undervalued stocks and sells short overvalued stocks",
    "Market neutral strategy maintains equal long and short exposure to eliminate market risk",
    "Convertible arbitrage buys convertible bonds and shorts underlying stock to capture pricing error",
    "Risk arbitrage also known as merger arbitrage profits from price spreads in M and A transactions",
    "Commodity trading advisor CTA uses systematic trend following strategies in futures markets",
    "Factor investing targets specific drivers of returns like value size momentum and quality",
    "Smart beta strategies combine passive indexing with active factor selection for excess returns",
    "ESG investing considers environmental social and governance factors in investment decisions",
    "Thematic investing focuses on specific trends like renewable energy artificial intelligence or healthcare",
    "Trading range and sideway market offer no clear trend but offer range trading opportunities",
    "Breakout trading enters positions when price moves beyond established support or resistance levels",
    "Pullback trading waits for temporary counter trend moves to enter in direction of main trend",
    
    # ── 经济学深入 ──
    "Supply side economics focuses on boosting economic growth by reducing taxes and regulation",
    "Keynesian economics advocates government intervention through fiscal and monetary policy to manage demand",
    "Monetarism emphasizes role of monetary policy focusing on controlling money supply to manage inflation",
    "Phillips curve shows inverse relationship between unemployment and inflation",
    "Laffer curve illustrates relationship between tax rates and government revenue",
    "Okun law states each one percent increase in unemployment reduces GDP by approximately two percent",
    "Gini coefficient measures income inequality within a population ranging from zero to one",
    "Purchasing power parity PPP theory states exchange rates should equalize price levels across countries",
    "Balance of payments records all economic transactions between residents of a country and rest of world",
    "Trade deficit occurs when imports exceed exports while trade surplus is opposite",
    "Fiscal policy uses government spending and taxation to influence economic conditions",
    "Monetary policy manages money supply and interest rates to achieve economic objectives",
    "Expansionary monetary policy lowers interest rates to stimulate borrowing and spending",
    "Contractionary monetary policy raises interest rates to control inflation and slow economy",
    "Forward guidance communicates central bank future policy intentions to influence market expectations",
    "Negative interest rates charge banks for holding excess reserves to encourage lending",
    "Helicopter money describes direct distribution of money to citizens to stimulate economy",
    "Yield curve control targets specific government bond yields through direct market intervention",
    "Stagflation combines high inflation high unemployment and slow economic growth",
    "Deflation is general decline in price levels often associated with economic recessions",
    "Hyperinflation extremely rapid price increases exceeding fifty percent per month",
    "GDP deflator measures price inflation across all goods and services in economy",
    
    # ── 固定收益深入 ──
    "Zero coupon bond pays no periodic interest and is sold at discount from face value",
    "TIPS Treasury Inflation Protected Securities adjust principal based on CPI inflation",
    "Floating rate note has variable coupon payments that adjust with reference interest rates",
    "Callable bond gives issuer right to redeem bond before maturity at specified price",
    "Puttable bond gives holder right to sell bond back to issuer before maturity at specified price",
    "Convertible bond can be exchanged for specified number of shares of issuing company stock",
    "Perpetual bond has no maturity date paying interest indefinitely to holder",
    "Sovereign bond is issued by national government in foreign currency creating exchange rate risk",
    "Green bond proceeds are used exclusively to finance environmentally friendly projects",
    "Pandemic bond is catastrophe bond specifically designed to fund pandemic response",
    "Credit default swap CDS is insurance against default of bond or other debt instrument",
    "Collateralized debt obligation CDO pools various debt instruments and issues tranches",
    "Mortgage backed security MBS pools mortgage loans and sells cash flows as securities",
    "Asset backed security ABS pools non mortgage assets like car loans and credit card debt",
    "Duration gap measures difference between asset and liability durations exposing interest rate risk",
    "Convexity measures curvature of price yield relationship improving duration approximation",
    "Credit rating assesses issuer ability to meet debt obligations AAA to D scale",
    "Yield spread measures yield difference between two bonds typically risk free vs corporate",
    "Bulldog bond is issued in UK by foreign issuer denominated in British pounds",
    "Samurai bond is yen denominated bond issued in Japan by foreign issuer",
    "Dim sum bond is renminbi denominated bond issued in Hong Kong by foreign issuer",
    "Panda bond is renminbi denominated bond issued in China by foreign issuer",

    # ── 期权与衍生品 ──
    "European option can only be exercised at expiration date while American option can be exercised anytime",
    "Option premium is price paid by buyer to seller for rights conveyed by option contract",
    "Intrinsic value of call option is stock price minus strike price if positive else zero",
    "Time value of option is premium minus intrinsic value representing potential for future profit",
    "Delta measures option price change relative to one dollar change in underlying asset price",
    "Gamma measures rate of change of delta per one dollar move in underlying asset",
    "Theta measures daily time decay of option value as expiration approaches",
    "Vega measures option price sensitivity to one percent change in implied volatility",
    "Rho measures option price sensitivity to one percent change in interest rate",
    "Implied volatility is market forecast of future volatility derived from option prices",
    "Volatility smile describes pattern where options at strike have lower implied volatility than OTM and ITM",
    "Black Scholes model calculates theoretical option price using five key inputs",
    "Binomial option pricing model values options using discrete time lattice approach",
    "Covered call strategy owns stock and sells call option to generate income",
    "Protective put strategy owns stock and buys put option as insurance against decline",
    "Straddle buys both call and put at same strike expecting large price movement either direction",
    "Strangle buys out of the money call and put expecting large price movement at lower cost",
    "Butterfly spread combines call or put spreads expecting low volatility and time decay profit",
    "Iron condor combines put credit spread and call credit spread for range bound market",
    "Calendar spread simultaneously buys and sells options with different expiration dates",
    "VIX options allow traders to trade volatility directly rather than directional price moves",
    "Exotic options include barrier lookback Asian and binary options with nonstandard features",
    
    # ── 期货与商品 ──
    "Futures margin is good faith deposit required to enter futures contract position",
    "Mark to market daily settling of gains and losses in futures trading accounts",
    "Basis is difference between futures price and spot price of underlying asset",
    "Backwardation occurs when futures price is below spot price for a commodity",
    "Contango occurs when futures price is above spot price for a commodity",
    "Gold has historically served as store of value and hedge against inflation",
    "Crude oil benchmark Brent and WTI are major grades with different pricing",
    "Natural gas prices are highly seasonal with winter demand peaks for heating",
    "Agricultural commodities include corn wheat soybeans coffee sugar and cotton",
    "Soft commodities are grown rather than mined including coffee cocoa and sugar",
    "Livestock futures include live cattle lean hogs and feeder cattle contracts",
    "Lumber futures track price of construction timber influenced by housing market",
    "Precious metals include gold silver platinum and palladium for investment and industrial use",
    "Base metals include copper aluminum zinc lead and nickel for industrial applications",
    "Iron ore is key steel making raw material priced based on grade and impurities",
    "Energy commodities include crude oil natural gas gasoline heating oil and coal",
    "Carbon credits allow emission of one tonne of carbon dioxide traded on exchanges",
    "Weather derivatives hedge against financial losses from adverse weather conditions",
    "Shipping freight futures track cost of transporting dry bulk goods on ocean routes",
    
    # ── 外汇市场 ──
    "Forex market is largest financial market with over six trillion dollars daily volume",
    "Major currency pairs include EUR USD GBP USD USD JPY and USD CHF",
    "Cross currency pairs exclude US dollar like EUR GBP EUR JPY and GBP JPY",
    "Exotic currency pairs involve emerging market currencies like USD TRY and USD ZAR",
    "Pip is smallest price move in forex market typically 0.0001 for most pairs",
    "Carry trade borrows low interest rate currency to invest in high interest rate currency",
    "Foreign exchange reserves are foreign currency deposits held by central banks",
    "Managed float allows currency value to fluctuate within bands set by central bank",
    "Currency peg fixes exchange rate of one currency to another or basket of currencies",
    "Currency board issues domestic currency fully backed by foreign currency reserves",
    "Dollarization occurs when country adopts US dollar as official currency",
    "Petrodollar recycling describes flow of oil revenues from oil producers to global markets",
    
    # ── 投资名人 ──
    "Warren Buffett is most famous value investor known for long term holdings through Berkshire Hathaway",
    "Benjamin Graham is father of value investing who taught at Columbia Business School",
    "Charlie Munger is vice chairman of Berkshire Hathaway known for multidisciplinary investing approach",
    "Peter Lynch managed Fidelity Magellan fund achieving 29 percent annual returns for thirteen years",
    "George Soros famously broke Bank of England in 1992 shorting ten billion pounds",
    "Ray Dalio founded Bridgewater Associates largest hedge fund based on principles of radical transparency",
    "John Bogle founded Vanguard Group pioneer of index fund investing for average investors",
    "Bill Ackman is activist investor who takes large positions and pushes for corporate changes",
    "Carl Icahn is legendary activist investor known for hostile takeovers and board seats",
    "David Einhorn founded Greenlight Capital known for value oriented hedge fund investing",
    "Jim Simons founder of Renaissance Technologies pioneered quantitative quantitative trading with Medallion Fund",
    "Paul Tudor Jones is macro trader famous for predicting 1987 market crash",
    "Michael Burry gained fame from predicting 2008 housing crisis featured in The Big Short",
    "Howard Marks is co founder of Oaktree Capital known for memos on market cycles",
    "Jack Bogle created first index mutual fund in 1976 revolutionizing passive investing for everyone",
    "Jesse Livermore was legendary early 1900s trader known for spectacular wins and losses",
    "Stanley Druckenmiller ran Duquesne Family Office with thirty percent average annual returns",
    "William O Neil founded Investor Business Daily and developed CAN SLIM investment system",
    "Larry Williams won World Cup Trading Championship turning ten thousand into one million",
    "Nicolas Darvas developed Darvas Box trading method while working as professional dancer",
    
    # ── 技术分析深入 ──
    "Elliott Wave theory describes market cycles as five wave impulse and three wave corrective patterns",
    "Dow theory identifies primary secondary and minor trends based on work of Charles Dow",
    "Wyckoff method analyzes accumulation and distribution phases through price and volume",
    "Point and figure chart uses X and O columns to filter out minor price movements",
    "Renko chart uses price boxes ignoring time and volume for trend clarity",
    "Heikin Ashi candles average price data to create smoother trend following charts",
    "On Balance Volume OBV uses volume flow to predict price movements",
    "Accumulation Distribution line combines price and volume to measure money flow",
    "Chaikin Money Flow measures volume weighted accumulation and distribution over period",
    "Elder rays use bull and bear power indicators developed by Alexander Elder",
    "Keltner channels use average true range to set channel width around exponential moving average",
    "Parabolic SAR sets trailing stop levels that accelerate as trend continues",
    "Average True Range ATR measures market volatility by calculating true range average",
    "Commodity Channel Index CCI measures current price level relative to average price over period",
    "Williams Percent Range WR measures overbought and oversold levels similar to stochastic",
    "Force Index combines price change and volume to measure strength of price moves",
    "Money Flow Index MFI uses price and volume to identify overbought and oversold conditions",
    "Stochastic RSI applies stochastic formula to RSI values for more sensitive readings",
    
    # ── 财务比率深入 ──
    "Quick ratio also acid test measures ability to meet short term obligations excluding inventory",
    "Cash ratio is most conservative liquidity measure comparing cash to current liabilities",
    "Asset turnover ratio measures efficiency of using assets to generate sales revenue",
    "Inventory turnover ratio shows how many times inventory is sold and replaced over period",
    "Receivables turnover ratio measures how effectively company collects accounts receivable",
    "Days sales outstanding DSO measures average number of days to collect payment after sale",
    "Return on assets ROA measures how profitable company is relative to its total assets",
    "Return on invested capital ROIC measures return generated on capital invested in business",
    "Economic value added EVA measures value created above required return of shareholders",
    "Dividend payout ratio measures percentage of earnings paid out as dividends to shareholders",
    "Dividend coverage ratio measures ability to pay dividends from net income",
    "Interest coverage ratio measures ability to pay interest on outstanding debt",
    "Fixed charge coverage ratio measures ability to cover fixed financial obligations",
    "Operating leverage measures sensitivity of operating income to changes in sales volume",
    "Financial leverage measures use of debt in company capital structure",
    "Total leverage combines operating and financial leverage measuring total risk",
    "DuPont analysis breaks return on equity into profit margin asset turnover and leverage components",
    "Sustainable growth rate measures how fast company can grow using internal resources",
    "Price to sales ratio compares company market value to its total sales revenue",
    "Price to cash flow ratio compares market price to operating cash flow per share",
    "Enterprise value to EBITDA is common valuation metric for company comparisons",
    "PEG ratio divides PE ratio by earnings growth rate to value growth companies",
    
    # ── 公司估值 ──
    "Discounted cash flow DCF valuation projects future cash flows and discounts to present value",
    "Dividend discount model DDM values stock based on present value of future dividends",
    "Gordon growth model values stock assuming constant dividend growth rate perpetually",
    "Comparable company analysis values company based on multiples of similar public companies",
    "Precedent transaction analysis values company based on prices paid in similar deals",
    "Leveraged buyout LBO analysis values company based on ability to service acquisition debt",
    "Liquidation value estimates net cash received if company assets were sold and debts paid",
    "Book value per share measures accounting value of each share of common stock",
    "Tangible book value per share excludes intangible assets like goodwill and patents",
    "Sum of parts valuation values conglomerate by separately valuing each business division",
    "Replacement cost values company based on cost to recreate its assets from scratch",
    "Market approach values asset based on market prices of comparable assets or transactions",
    "Income approach values asset based on present value of future income streams",
    "Cost approach values asset based on cost to construct or replace the asset",
    "Terminal value represents value beyond explicit forecast period in DCF analysis",
    "Weighted average cost of capital WACC is discount rate reflecting cost of all capital sources",
    "Cost of equity is return required by shareholders based on stock risk",
    "Capital asset pricing model CAPM calculates cost of equity using beta and market risk premium",
    
    # ── 并购与企业行动 ──
    "Merger combines two companies into single new entity with shared ownership",
    "Acquisition occurs when one company purchases controlling stake in another company",
    "Takeover is acquisition where acquiring company assumes control of target company",
    "Hostile takeover proceeds against target management wishes often through tender offer",
    "Friendly merger has mutual agreement and approval from both companies boards",
    "Horizontal merger combines two companies in same industry and market segment",
    "Vertical merger combines buyer and seller along supply chain for efficiency gains",
    "Conglomerate merger combines unrelated businesses to diversify revenue streams",
    "Reverse merger private company acquires public shell to bypass IPO process",
    "Leveraged buyout LBO uses significant borrowed funds to acquire controlling stake",
    "Management buyout MBO existing management team purchases company from current owners",
    "Spin off distributes shares of subsidiary to parent company shareholders creating independent company",
    "Split off offers parent company shareholders choice to exchange shares for subsidiary shares",
    "Carve out sells minority stake in subsidiary through public offering retaining parent control",
    "Tracking stock trades based on performance of specific division within larger company",
    "Tender offer is public offer to purchase shares directly from shareholders at premium",
    "Golden parachute provides lucrative benefits to executives if company is acquired",
    "Poison pill dilutes acquirers shares by allowing other shareholders to buy at discount",
    "White knight is friendly acquirer sought by target company to avoid hostile takeover",
    "Greenmail is premium paid by target company to repurchase shares from hostile acquirer",
    
    # ── 风险类型 ──
    "Systematic risk affects entire market and cannot be diversified away",
    "Unsystematic risk is specific to company or industry and can be reduced through diversification",
    "Market risk exposure to overall stock market movements affecting all securities",
    "Credit risk possibility that borrower fails to meet debt obligations",
    "Liquidity risk inability to buy or sell asset quickly without significant price concession",
    "Operational risk loss from inadequate internal processes systems or external events",
    "Legal risk arises from lawsuits regulatory actions or contractual disputes",
    "Regulatory risk changes in regulations that negatively affect business operations or value",
    "Country risk political and economic instability in foreign country affecting investments",
    "Currency risk exchange rate fluctuations affecting value of foreign currency denominated assets",
    "Interest rate risk bond prices move inversely to interest rates affecting portfolio values",
    "Reinvestment risk future cash flows must be reinvested at lower prevailing interest rates",
    "Prepayment risk borrowers repay loans early reducing expected interest income",
    "Longevity risk outliving retirement savings due to longer than expected lifespan",
    "Sequencing risk timing of investment returns affects portfolio value in retirement drawdown",
    
    # ── 退休与养老金 ──
    "401k plan is employer sponsored defined contribution retirement savings plan in United States",
    "IRA Individual Retirement Account provides tax advantages for retirement savings",
    "Roth IRA contributions are made with after tax dollars and withdrawals are tax free",
    "Defined benefit plan pays specified monthly benefit at retirement based on salary and years",
    "Defined contribution plan participants and employers contribute to individual accounts",
    "Social Security is government program providing retirement disability and survivor benefits",
    "Pension fund pools contributions to provide retirement income for employees",
    "Sovereign wealth fund SWF is state owned investment fund managing national savings",
    "Annuity is insurance product providing guaranteed income stream for specified period",
    "Required minimum distribution RMD is minimum amount must withdraw from retirement accounts after age",
    
    # ── 个人理财 ──
    "Emergency fund holds three to six months living expenses in liquid accounts for unexpected events",
    "Compound interest earns interest on previously earned interest creating exponential growth",
    "Rule of 72 estimates years to double money by dividing 72 by annual interest rate",
    "Net worth equals total assets minus total liabilities measuring personal financial health",
    "Debt avalanche pays highest interest rate debt first minimizing total interest paid",
    "Debt snowball pays smallest balance first building momentum through quick wins",
    "Amortization schedule shows loan payment breakdown between principal and interest over time",
    "Credit score numerically summarizes creditworthiness based on payment history and utilization",
    "FICO score ranges from 300 to 850 used by lenders to evaluate credit risk",
    "Asset allocation model recommends stock bond cash mix based on age risk tolerance and goals",
    "Target date fund automatically adjusts asset allocation as target retirement date approaches",
    "Tax loss harvesting sells losing investments to offset taxable capital gains",
    "Roth conversion ladder converts traditional IRA to Roth IRA gradually to manage taxes",
    "Side hustle is secondary income stream pursued alongside primary employment",
    "Passive income requires minimal ongoing effort like rental income dividends or royalties",
    
    # ── 保险 ──
    "Term life insurance provides coverage for specified period with no cash value accumulation",
    "Whole life insurance combines death benefit with savings component accumulating cash value",
    "Universal life insurance offers flexible premiums and adjustable death benefit with cash value",
    "Variable life insurance cash value invested in sub accounts with market exposure choices",
    "Health insurance covers medical expenses through premiums deductibles and co payments",
    "Disability insurance replaces portion of income if unable to work due to illness or injury",
    "Long term care insurance covers cost of assisted living nursing home or home care services",
    "Property insurance covers damage to buildings and personal property from specified perils",
    "Liability insurance protects against claims resulting from injuries or damage to others",
    "Umbrella insurance provides additional liability coverage beyond underlying policy limits",
    
    # ── 税务 ──
    "Progressive tax system tax rate increases as taxable income rises",
    "Marginal tax rate is tax rate applied to each additional dollar of income earned",
    "Effective tax rate is total tax paid divided by total income expressed as percentage",
    "Capital gains tax applies to profit from sale of assets held for investment",
    "Short term capital gains on assets held less than one year taxed as ordinary income",
    "Long term capital gains on assets held over one year taxed at preferential rates",
    "Dividend tax qualified dividends taxed at capital gains rates non qualified at ordinary rates",
    "Tax deductible contributions to retirement accounts reduce current year taxable income",
    "Tax credit directly reduces tax liability dollar for dollar more valuable than deduction",
    "Standard deduction fixed amount subtracted from adjusted gross income reducing taxable income",
    "Itemized deductions include mortgage interest charitable contributions and medical expenses",
    "Alternative minimum tax AMT ensures high income taxpayers pay minimum tax amount",
    "Estate tax applies to transfer of wealth at death above exemption threshold",
    "Gift tax applies to transfers of money or property during lifetime above annual exclusion",
    "Trust legal entity holding assets for benefit of beneficiaries with tax implications",

    # ── 行为金融学 ──
    "Loss aversion investors feel pain of losses roughly twice as strongly as pleasure of gains",
    "Anchoring bias relies too heavily on first piece of information encountered when making decisions",
    "Confirmation bias seeks information confirming existing beliefs while ignoring contradictory evidence",
    "Herd mentality investors follow crowd rather than independent analysis leading to bubbles and crashes",
    "Overconfidence bias leads investors to overestimate their knowledge ability and prediction accuracy",
    "Recency bias gives greater weight to recent events than historical patterns in decision making",
    "Availability heuristic overestimates likelihood of events that are easily recalled",
    "Disposition effect tendency to sell winning stocks too early and hold losing stocks too long",
    "Mental accounting treats money differently depending on source or intended use rather than holistically",
    "Sunk cost fallacy continues investing in losing position because of past committed resources",
    "Endowment effect values assets more highly simply because they are owned",
    "Framing effect decisions are influenced by how choices are presented as gains or losses",
    "Hindsight bias believes past events were predictable after they have occurred",
    "Self attribution bias credits successes to personal skill while blaming failures on external factors",
    "Gamblers fallacy believes past random events affect probabilities of future random events",
    
    # ── 金融历史 ──
    "Tulip mania in 1630s Netherlands was first recorded speculative bubble with tulip bulb prices",
    "South Sea bubble 1720 British company stock collapsed after speculation in South American trade",
    "Wall Street Crash of 1929 triggered Great Depression with Dow losing 89 percent from peak",
    "Black Monday 1987 Dow Jones dropped 22.6 percent in single day largest percentage decline",
    "Japanese asset price bubble 1990 Nikkei lost 80 percent after land and stock speculation",
    "Asian financial crisis 1997 currency devaluations spread across Thailand Indonesia and South Korea",
    "Dot com bubble 2000 NASDAQ lost 78 percent after internet company speculation collapsed",
    "Global financial crisis 2008 triggered by US housing bubble and subprime mortgage defaults",
    "European debt crisis 2010 Greece Ireland and Portugal required bailouts after sovereign debt issues",
    "Flash crash 2010 Dow dropped 1000 points in minutes before quickly recovering",
    "Chinese stock market crash 2015 Shanghai Composite lost 40 percent in three months",
    "COVID crash March 2020 global markets fell over 30 percent in fastest bear market ever",
    "Cryptocurrency crash 2022 Bitcoin lost over 70 percent after speculative bubble burst",
    "Silver Thursday 1980 Hunt brothers attempted to corner silver market causing massive losses",
    "Barings Bank collapse 1995 Nick Leeson unauthorized trading caused 233 year old bank failure",
    "LTCM collapse 1998 Long Term Capital Management hedge fund failed requiring Fed orchestrated bailout",
    "Enron scandal 2001 accounting fraud led to bankruptcy of major energy trading company",
    "Madoff Ponzi scheme 2008 revealed as largest financial fraud in history at 65 billion dollars",
    "LIBOR scandal 2012 banks manipulated benchmark interest rate affecting trillions in contracts",
    "GameStop short squeeze 2021 retail investors coordinated through Reddit squeezed hedge fund shorts",
    
    # ── 会计基础 ──
    "Accrual accounting records revenues and expenses when earned or incurred not when cash changes",
    "Cash accounting records transactions only when cash is received or paid out",
    "GAAP Generally Accepted Accounting Principles are standard accounting rules in United States",
    "IFRS International Financial Reporting Standards are global accounting standards used in many countries",
    "Double entry bookkeeping every transaction affects at least two accounts with equal debits and credits",
    "Depreciation allocates cost of tangible asset over its useful life period",
    "Amortization allocates cost of intangible asset over its useful life period",
    "Goodwill represents premium paid over fair value in acquisition of another company",
    "Intangible assets lack physical substance including patents trademarks and copyrights",
    "Deferred revenue represents cash received for services not yet performed",
    "Accounts receivable are amounts owed by customers for goods or services delivered",
    "Accounts payable are amounts company owes to suppliers for goods or services received",
    "Accumulated depreciation is total depreciation taken on asset since purchase",
    "Retained earnings are cumulative net income not distributed as dividends to shareholders",
    "Treasury stock is shares that were issued and subsequently repurchased by company",
    "Operating lease records rental expense without showing asset or liability on balance sheet",
    "Capital lease records both asset and liability on balance sheet transferring ownership risks",
    "LIFO Last In First Out inventory method assumes newest items sold first",
    "FIFO First In First Out inventory method assumes oldest items sold first",
    "Lower of cost or market rule requires inventory valued at lower of purchase cost or market value",
]

# ════════════════════════════════════════════
# 写入知识文件
# ════════════════════════════════════════════

def write_knowledge(knowledge_list, prefix):
    existing = [f for f in os.listdir(KNOWLEDGE_DIR) if f.endswith('.txt')]
    nums = []
    for f in existing:
        try:
            nums.append(int(f.split('_')[0]))
        except ValueError:
            pass
    start_idx = max(nums) + 1 if nums else 1
    
    for i, text in enumerate(knowledge_list):
        idx = start_idx + i
        fname = f"{idx:06d}_{prefix}_{i+1:04d}.txt"
        path = os.path.join(KNOWLEDGE_DIR, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text.strip())
    return len(knowledge_list), start_idx

n, start = write_knowledge(KNOWLEDGE, "finance_more")
print(f"✅ 新增 {n} 条金融知识 (从索引 {start} 开始)")
print(f"📂 knowledge_base/ 总文件数: {len([f for f in os.listdir(KNOWLEDGE_DIR) if f.endswith('.txt')])}")
